### PR TITLE
Update to use hawk credentails for treeherder projects

### PR DESCRIPTION
**Pull request by gregarndt**

### CODE REVIEW

**Comment by gregarndt** [comment]
@jonasfj Would you mind just looking at this?  There really isn't many active people on gaia-taskcluster anymore to review things, and I think these changes are small.  Basically doing the same things that mozilla-taskcluster is doing with the new client.

**Comment by gregarndt** [comment]
Pete, would you be able to take a look at this? There's not many people that have contributed to this repo, so it's all up in the air :) as long as things seem sane, I can deploy and see if things work.

**Comment by jonasfj** [comment]
@gregarndt, this looks okay to me... try it out `r+`.
@nullaus is probably the person who will complain if this doesn't work... maybe he is even the owner, who knows :)

**Comment by jonasfj** [comment]
Sorry, about being super slow...

**Comment by petemoore** [comment]
@gregarndt sorry for not spotting this sooner - thanks @jonasfj for taking care of it!

**Pull request merged**
